[mypy]
python_version = 3.11
namespace_packages = true
explicit_package_bases = true

[mypy-homeassistant.*]
ignore_missing_imports = true

[mypy-elkm1_lib.*]
ignore_missing_imports = true

[mypy-serial.*]
ignore_missing_imports = true
