name: Validate

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install -r requirements-dev.txt
      - run: ruff check custom_components/elkm1
      - run: black --check custom_components/elkm1
      - run: mypy custom_components/elkm1
      - run: pytest tests/
